config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  resources :ocr_documents, only: %i[new create show] do
    get 'search', on: :member
  end

  root to: 'ocr_documents#new'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ocr_document.rb
# frozen_string_literal: true

class OcrDocument < ApplicationRecord
  has_many :text_extractions, dependent: :destroy
  has_one_attached :original_image
  has_one_attached :generated_image

  validate :acceptable_image

  after_commit :process_on_after_create_commit, on: :create

  def original_image_path
    Rails.application.routes.url_helpers.url_for(original_image)
  end

  private

  def process_on_after_create_commit
    OcrDocuments::ExtractHocrDataJob.perform_later(id, true)
  end

  def acceptable_image
    return unless original_image.attached?

    errors.add(:original_image, 'is too big') unless original_image.blob.byte_size <= 1.megabyte

    return if ['image/png'].include?(original_image.content_type)

    errors.add(:original_image, 'must be a PNG')
  end
end

app/models/text_extraction.rb
# frozen_string_literal: true

class TextExtraction < ApplicationRecord
  belongs_to :ocr_document

  validates :word, presence: true
  validates :confidence, presence: true,
                         numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validates :x_start, :y_start, :x_end, :y_end, presence: true,
                                                numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController is the base class for all controllers in the application.
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning
end

app/controllers/ocr_documents_controller.rb
# frozen_string_literal: true

# OcrDocumentsController handles the creation, display, and search of OCR documents.
class OcrDocumentsController < ApplicationController
  before_action :find_ocr_document, only: %i[show search]

  def new
    @ocr_document = OcrDocument.new
  end

  def create
    @ocr_document = OcrDocument.new(ocr_document_params)
    if @ocr_document.save
      redirect_to @ocr_document, notice: 'Ocr document processing has been started.'
    else
      flash.now[:alert] = 'Failed to save the OCR document.'
      render :new
    end
  end

  def show; end

  def search
    @search_query = params[:query]

    respond_to do |format|
      format.json do
        if @ocr_document.present? && @search_query.present?
          render json: OcrDocuments::TextSearch.call(@ocr_document.id, @search_query)
        else
          render json: { error: 'No data found' }, status: :unprocessable_entity
        end
      end
    end
  end

  private

  def find_ocr_document
    @ocr_document = OcrDocument.find_by(id: params[:id])

    return if @ocr_document.present?

    flash.now[:alert] = 'OCR document not found.'
    redirect_to root_path
  end

  def ocr_document_params
    params.require(:ocr_document).permit(:original_image)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageOcrApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>  
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/ocr_documents/new.html.erb
<div class="form-container">
  <%= form_with(model: @ocr_document, url: ocr_documents_path, method: :post, local: true) do |form| %>
    <h3>hOCR Processing App</h3>
    <div class="form-field">
      <%= form.label :original_image, "Upload Image" %>
      <%= form.file_field :original_image %>
    </div>
    <div class="form-field">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/ocr_documents/show.html.erb
<h2 class="image-heading"> hOCR Processed Images</h2>

<% if @ocr_document&.hocr_processed_at.present? %>
  <div class="search-container" data-controller="ocr-documents">
    <h4>Search the document : </h4>
    <form action="#" data-action="submit->ocr-documents#search" data-ocr-document-id="<%= params[:id] %>">
      <input type="text" placeholder="Search the document" data-ocr-documents-target="params">
      <button type="submit">Search</button>
    </form>
  </div>
<% end %>

<div class="image-container">
    <div class="image-wrapper">
        <h4>Original Image (<%= link_to 'Download', rails_blob_path(@ocr_document.original_image, disposition: 'attachment') %> )</h4>
        <%= image_tag @ocr_document.original_image, id: "original-image", class: "responsive-image" %>
        <canvas id="imageCanvas"></canvas>
    </div>

    <div class="image-wrapper">
        <% if @ocr_document.generated_image.attached? %>
            <h4>Marked Image (<%= link_to 'Download', rails_blob_path(@ocr_document.generated_image, disposition: 'attachment') %> )</h4>
            <%= image_tag @ocr_document.generated_image, class: "responsive-image" %>
        <% else %>
            <h4>Marked Image (Being processed, please refresh in a moment!!)</h4>
            <div class="loading-container">
                <%= image_tag "Infinity-1s-200px.gif", class: "loading-image" %>
            </div>
        <% end %>
    </div>
</div>